fieldLayouts:
  af3c3a34-13f9-4fee-9d52-84d591b76b2c:
    tabs:
      -
        elements:
          -
            fieldUid: 0499506a-3693-406c-9bff-a04abe18daa2
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Branding
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4dbc61da-b1a5-4dfb-a41d-bcb588f594d6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Important Settings'
        sortOrder: 2
handle: siteSettings
name: 'Site Settings'
