fieldLayouts:
  af3c3a34-13f9-4fee-9d52-84d591b76b2c:
    tabs:
      -
        elements:
          -
            fieldUid: 25962328-dd7c-4c17-acf8-cb9a6e2386ce # Newsletter Signup - Popup Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8d852626-21ab-4f69-88a2-d57479b72c06 # Newsletter Signup - Popup Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Newsletter Signup Popup'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 0499506a-3693-406c-9bff-a04abe18daa2 # Logo
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4dbc61da-b1a5-4dfb-a41d-bcb588f594d6 # Footer Copyright
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Site Settings'
        sortOrder: 2
handle: siteSettings
name: 'Site Settings'
