childBlocks: ''
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  c8e26a5a-28cc-4494-9300-44715700c3d9:
    tabs:
      -
        elements:
          -
            fieldUid: 2886f198-65b5-4662-8f31-5bc761325b03
            instructions: 'The link to use for this button'
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: adac64af-2715-4c2c-aad7-d563dea9e9c0
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e98e2c64-af99-46b8-b4c7-2748aff3f3e5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Button Settings'
        sortOrder: 1
handle: button
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 2
name: Button
sortOrder: 23
topLevel: false
