childBlocks: ''
field: 720308b0-c8fd-4f13-bd94-758097e76b5e # Content Builder
fieldLayouts:
  30d3320c-7edb-4f57-9c2e-30b26efd9107:
    tabs:
      -
        elements:
          -
            fieldUid: 7fa651e8-fda7-4c83-84ae-a464c36b020f # Section Type
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 56aa0bec-30e7-42ff-b25e-ad77bfa5d907 # HTML
            instructions: 'The HTML code to use for this section. Be careful to use safe code - this will be embedded directly into the web page. '
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: custom_html
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Custom HTML'
sortOrder: 25
topLevel: true
