childBlocks: null
field: 720308b0-c8fd-4f13-bd94-758097e76b5e # Content Builder
fieldLayouts:
  e6053033-ef0b-4d39-b9fd-21341c735ac7:
    tabs:
      -
        elements:
          -
            fieldUid: 7fa651e8-fda7-4c83-84ae-a464c36b020f # Section Type
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 68443fb6-c3e8-4e35-b120-cb8e0f687d08 # Event
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e2c4db88-dd14-49a8-81d5-1c41ab06be6e # Use custom content?
            instructions: 'If enabled, event will be hidden after the end date of the event has passed. '
            label: 'Hide event if event date has passed?'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: featured_event
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Featured Event'
sortOrder: 32
topLevel: true
