childBlocks:
  - button
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  09089ab4-ba7c-4f64-b2e9-6e7ccc9c248b:
    tabs:
      -
        elements:
          -
            fieldUid: f7a6d15c-0dbc-4167-ac30-a19f8f45491d
            instructions: 'The background image for this section'
            label: 'Background Image'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: hero
maxBlocks: 0
maxChildBlocks: 2
maxSiblingBlocks: 0
name: Hero
sortOrder: 6
topLevel: true
