childBlocks: ''
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  4d41ed7d-4536-4f90-94e6-5c551b65ac2e:
    tabs:
      -
        elements:
          -
            fieldUid: 5ac27dca-bb4c-4e88-a8a3-5fb6621bfe93
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 291580b7-d5d0-4340-8f73-76b8fcf000d1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2886f198-65b5-4662-8f31-5bc761325b03
            instructions: ''
            label: 'Link (optional)'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: icon_item
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Icon Item'
sortOrder: 26
topLevel: false
