childBlocks: ''
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  f02e82c2-f8e0-4a46-86c2-f1c29179c6ae:
    tabs:
      -
        elements:
          -
            fieldUid: 5ac27dca-bb4c-4e88-a8a3-5fb6621bfe93
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 291580b7-d5d0-4340-8f73-76b8fcf000d1
            instructions: ''
            label: Text
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: icon_list_item
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Icon List Item'
sortOrder: 47
topLevel: false
