childBlocks:
  - text_icon_item
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  c424c4d1-5f00-4fca-9a4e-993cead06790:
    tabs:
      -
        elements:
          -
            fieldUid: 7fa651e8-fda7-4c83-84ae-a464c36b020f
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: ''
            label: ''
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: icon_text_grid
maxBlocks: 0
maxChildBlocks: 12
maxSiblingBlocks: 0
name: 'Text Icon Grid'
sortOrder: 21
topLevel: true
