childBlocks:
  - image_gallery_item
field: 720308b0-c8fd-4f13-bd94-758097e76b5e # Content Builder
fieldLayouts:
  f02cfb9b-1b3e-472a-a0a3-6615d1b60460:
    tabs:
      -
        elements:
          -
            fieldUid: 7fa651e8-fda7-4c83-84ae-a464c36b020f # Section Type
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: image_gallery
maxBlocks: 0
maxChildBlocks: 21
maxSiblingBlocks: 0
name: 'Image Gallery'
sortOrder: 14
topLevel: true
