childBlocks:
  - button
  - image_stats_banner_statistic
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  5bce36ab-7561-4a24-8a7c-dedd15429325:
    tabs:
      -
        elements:
          -
            fieldUid: 7fa651e8-fda7-4c83-84ae-a464c36b020f
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: af8a1c7e-dac5-4182-9acd-7854cba44b17
            instructions: 'Standard will show the image on the left and the text on the right, and Reversed will show the image on the right and text on the left.  '
            label: 'Image Position'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f7a6d15c-0dbc-4167-ac30-a19f8f45491d
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 104a2117-39ef-4ed6-b367-0c0db83b87be
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: image_text_stats_banner
maxBlocks: 0
maxChildBlocks: 3
maxSiblingBlocks: 0
name: 'Image/Stats/Text Banner'
sortOrder: 25
topLevel: true
