childBlocks: ''
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  2bf4b8f1-2d71-4cac-af49-60c36142f5ea:
    tabs:
      -
        elements:
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: 'The primary statistic to show ($500, 2700+, etc)'
            label: Statistic
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89
            instructions: 'More information about the above statistic (ie, "parents reunited with their children", "families adopted for christmas"). '
            label: Description
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e2c4db88-dd14-49a8-81d5-1c41ab06be6e
            instructions: 'If enabled, statistic will be shown with a colored background, for emphasis. '
            label: 'Highlight statistic?'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: image_stats_banner_statistic
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Statistic
sortOrder: 39
topLevel: false
