childBlocks:
  - button
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  cae44aa8-c582-4ab4-bec9-c4f7204190c6:
    tabs:
      -
        elements:
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 291580b7-d5d0-4340-8f73-76b8fcf000d1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: inline_hero_columns_item
maxBlocks: 0
maxChildBlocks: 1
maxSiblingBlocks: 0
name: 'Inline Hero/Columns Item'
sortOrder: 54
topLevel: false
