childBlocks: ''
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  521c827f-733c-4071-915d-898ca2dfc106:
    tabs:
      -
        elements:
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: 'The name of the company represented by this logo.'
            label: 'Company Name'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f7a6d15c-0dbc-4167-ac30-a19f8f45491d
            instructions: 'The logo to display'
            label: Logo
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d7af6a87-c305-4903-b8bd-34ca93b30179
            instructions: 'The website URL to use for this logo'
            label: 'Website URL'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: logoListItem
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Logo List Item'
sortOrder: 33
topLevel: false
