childBlocks: ''
field: 720308b0-c8fd-4f13-bd94-758097e76b5e # Content Builder
fieldLayouts:
  9adcd620-a19f-45e4-a50b-3e754189a1d0:
    tabs:
      -
        elements:
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574 # Heading
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 104a2117-39ef-4ed6-b367-0c0db83b87be # Formatted Content
            instructions: 'The content to display next to this item. Keep character count down, space is limited. '
            label: 'Short Content'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: map_text_item
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Map/Text Item'
sortOrder: 50
topLevel: false
