childBlocks:
  - map_text_item
field: 720308b0-c8fd-4f13-bd94-758097e76b5e # Content Builder
fieldLayouts:
  3a25d697-09f9-4246-abaf-592fea31690b:
    tabs:
      -
        elements:
          -
            fieldUid: 7fa651e8-fda7-4c83-84ae-a464c36b020f # Section Type
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b95a16bc-39e5-4914-a385-86b644433d63 # Address
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e2c4db88-dd14-49a8-81d5-1c41ab06be6e # Use custom content?
            instructions: 'If enabled, will display social icons (in the same format as the Map/Text Item nested blocks).'
            label: 'Show social media icons?'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89 # Subheading
            instructions: ''
            label: Subheading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574 # Heading
            instructions: ''
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 104a2117-39ef-4ed6-b367-0c0db83b87be # Formatted Content
            instructions: ''
            label: 'Formatted Content'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: map_text
maxBlocks: 0
maxChildBlocks: 3
maxSiblingBlocks: 0
name: Map/Text
sortOrder: 29
topLevel: true
