childBlocks: ''
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  0e910be5-e42d-484a-81c5-bb6fdcdbb4e9:
    tabs:
      -
        elements:
          -
            fieldUid: b95a16bc-39e5-4914-a385-86b644433d63
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: 'The name of the location to display above this map item.'
            label: 'Location Name'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: map_grid_item
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Map Grid Item'
sortOrder: 39
topLevel: false
