childBlocks:
  - points_table
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  b8a39046-b394-4498-aa12-42d4ee106c23:
    tabs:
      -
        elements:
          -
            fieldUid: 7fa651e8-fda7-4c83-84ae-a464c36b020f
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: points_table_list
maxBlocks: 0
maxChildBlocks: 10
maxSiblingBlocks: 0
name: 'Points Table List'
sortOrder: 27
topLevel: true
