childBlocks: ''
field: 720308b0-c8fd-4f13-bd94-758097e76b5e # Content Builder
fieldLayouts:
  01ad5d5c-3674-4b63-9458-5407167ee272:
    tabs:
      -
        elements:
          -
            fieldUid: 104a2117-39ef-4ed6-b367-0c0db83b87be # Formatted Content
            instructions: ''
            label: 'Row Description'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574 # Heading
            instructions: 'The points value for this row. '
            label: 'Row Points'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: points_table_item
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Points Table Row'
sortOrder: 54
topLevel: false
