childBlocks:
  - points_table_item
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  c43a7b0a-a89a-4def-8d38-d4b02945f57b:
    tabs:
      -
        elements:
          -
            fieldUid: 5ac27dca-bb4c-4e88-a8a3-5fb6621bfe93
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89
            instructions: 'The heading to display over the description column (for example, Budget Activity)'
            label: 'Column Description Heading'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 104a2117-39ef-4ed6-b367-0c0db83b87be
            instructions: 'A short description of terms or notes.'
            label: Terms/Notes
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: points_table
maxBlocks: 10
maxChildBlocks: 10
maxSiblingBlocks: 0
name: 'Points Table'
sortOrder: 41
topLevel: false
