childBlocks: ''
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  c8e35b73-4eff-4984-8249-39404fbdac14:
    tabs:
      -
        elements:
          -
            fieldUid: 7fa651e8-fda7-4c83-84ae-a464c36b020f
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 56aa0bec-30e7-42ff-b25e-ad77bfa5d907
            instructions: 'The QGive widget embed code - found under Settings > Widgets in the QGive admin (you can add new ones for existing forms by clicking Add New Widget at the top). Make sure the page URL in the widget settings exactly matches the page URL that you''ll be adding this form to. '
            label: 'QGive Embed Code'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: qgive_form
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'QGive Form'
sortOrder: 29
topLevel: true
