childBlocks:
  - team_text_grid_item
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  b5d640b4-9c9d-4a6e-8ac3-9b75f83ed5ec:
    tabs:
      -
        elements:
          -
            fieldUid: 7fa651e8-fda7-4c83-84ae-a464c36b020f
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: team_text_grid
maxBlocks: 0
maxChildBlocks: 24
maxSiblingBlocks: 0
name: 'Team Text Grid'
sortOrder: 18
topLevel: true
