childBlocks: ''
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  4a01d3b3-153e-4137-9600-3c2352080b0d:
    tabs:
      -
        elements:
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: 'The name (and potentially title) to use for this team member.'
            label: Name
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89
            instructions: 'The title to use for this team member (ie, job position or company name)'
            label: Title
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: team_text_grid_item
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Team Member'
sortOrder: 37
topLevel: false
