childBlocks:
  - team_grid_item
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  9bcac3dc-539b-49a9-a0ab-43c7f89ed6c2:
    tabs:
      -
        elements:
          -
            fieldUid: 7fa651e8-fda7-4c83-84ae-a464c36b020f
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e2c4db88-dd14-49a8-81d5-1c41ab06be6e
            instructions: 'Enable to show larger portraits (rows of 2 instead of rows of 3) - helpful for featuring this specific set of team members before a smaller list of others. '
            label: 'Show as large portraits? '
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: team_grid
maxBlocks: 0
maxChildBlocks: 12
maxSiblingBlocks: 0
name: 'Team Grid'
sortOrder: 17
topLevel: true
