childBlocks:
  - button
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  d916a483-225c-458f-8fa9-b8e95f35f00a:
    tabs:
      -
        elements:
          -
            fieldUid: 7fa651e8-fda7-4c83-84ae-a464c36b020f
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 291580b7-d5d0-4340-8f73-76b8fcf000d1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: text_cta
maxBlocks: 0
maxChildBlocks: 2
maxSiblingBlocks: 0
name: 'Text CTA'
sortOrder: 8
topLevel: true
