childBlocks: ''
field: 720308b0-c8fd-4f13-bd94-758097e76b5e
fieldLayouts:
  9962b7ce-e845-4586-b705-942192df5022:
    tabs:
      -
        elements:
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 104a2117-39ef-4ed6-b367-0c0db83b87be
            instructions: 'A short phrase of text to show underneath this heading. '
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: text_icon_item
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Text Icon Item'
sortOrder: 43
topLevel: false
