childBlocks: ''
field: 720308b0-c8fd-4f13-bd94-758097e76b5e # Content Builder
fieldLayouts:
  b0e50832-0033-42d5-b04e-a89b3a2bdeb8:
    tabs:
      -
        elements:
          -
            fieldUid: 7fa651e8-fda7-4c83-84ae-a464c36b020f # Section Type
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 744cb779-6599-47be-b369-d180c2f4b780 # Section Width
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f7a6d15c-0dbc-4167-ac30-a19f8f45491d # Image
            instructions: 'The preview image to use for this section (shown as a background image, usually a still from the video you''d like to display). '
            label: 'Preview Image'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdce38f5-80cc-4912-a2f7-d3594f32cb89 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040f755c-ead7-4a88-bf98-e0a117b05574 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d7af6a87-c305-4903-b8bd-34ca93b30179 # URL
            instructions: 'The URL of the video you''d like to display (YouTube and Vimeo work best). '
            label: 'Video URL'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: video
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Video Hero'
sortOrder: 16
topLevel: true
