enableVersioning: true
handle: blogSingle
name: 'Blog '
propagationMethod: all
siteSettings:
  0cc785f8-a672-4448-9841-1c39b72f75bd:
    enabledByDefault: true
    hasUrls: true
    template: _pages/blog/blog
    uriFormat: blog
type: single
