enableVersioning: true
handle: eventsSingle
name: 'Events Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - Preview
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0cc785f8-a672-4448-9841-1c39b72f75bd: # Dover Development
    enabledByDefault: true
    hasUrls: true
    template: _pages/events/events
    uriFormat: events-calendar
type: single
