enableVersioning: true
handle: home
name: Home
previewTargets: null
propagationMethod: all
siteSettings:
  0cc785f8-a672-4448-9841-1c39b72f75bd:
    enabledByDefault: true
    hasUrls: true
    template: _pages/home
    uriFormat: __home__
type: single
