enableVersioning: true
handle: partners
name: Partners
propagationMethod: all
siteSettings:
  0cc785f8-a672-4448-9841-1c39b72f75bd: # Dover Development
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 531dd504-b863-4ef1-af38-c693730f1470
type: structure
