contentColumnType: string(800)
fieldGroup: 63c84b53-059e-46e3-b41e-3cd1cb9030fe
handle: addressText
instructions: 'Enter the full address of the location to display for this section - we recommend searching for the location on Google Maps, then copying the full address (including the business name).'
name: Address
searchable: false
settings:
  byteLimit: null
  charLimit: 200
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Hillcrest Hope, 123 Example St, Liberty MO 64068'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
