contentColumnType: string
fieldGroup: 63c84b53-059e-46e3-b41e-3cd1cb9030fe # Content Builder Fields
handle: email
instructions: 'The email address to use for this section. '
name: Email
searchable: true
settings:
  placeholder: hello@example.com
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
