contentColumnType: text
fieldGroup: 5ced9d30-29a3-4b23-8b74-4951c818fb67 # SEO
handle: eventSeo
instructions: 'The SEO setup for this event'
name: 'Event SEO'
searchable: true
settings:
  description: '{seoDescription}'
  hideSocial: ''
  robots:
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
  socialImage: ''
  suffixAsPrefix: null
  title:
    -
      __assoc__:
        -
          - key
          - '1'
        -
          - locked
          - '0'
        -
          - template
          - '{title}'
    -
      __assoc__:
        -
          - key
          - '2'
        -
          - locked
          - '1'
        -
          - template
          - ' | {{ siteName }}'
  titleSuffix: null
translationKeyFormat: null
translationMethod: none
type: ether\seo\fields\SeoField
