contentColumnType: text
fieldGroup: 7fa5e5f4-59ab-4c6f-9d42-8f827e5e4565 # Globals
handle: footerCopyright
instructions: 'The copyright text to place in the site footer. Use ${year} to show the current year. '
name: 'Footer Copyright'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: TextWithFormatting.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
