contentColumnType: string(600)
fieldGroup: 63c84b53-059e-46e3-b41e-3cd1cb9030fe
handle: heading
instructions: 'The primary heading for this section.'
name: Heading
searchable: true
settings:
  byteLimit: null
  charLimit: 150
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
