contentColumnType: string
fieldGroup: 63c84b53-059e-46e3-b41e-3cd1cb9030fe
handle: image
instructions: 'The image for this section. '
name: Image
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:47d806d7-f955-46cc-9e24-88e5a9334137'
  defaultUploadLocationSubpath: general
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Select an image'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:47d806d7-f955-46cc-9e24-88e5a9334137'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:47d806d7-f955-46cc-9e24-88e5a9334137'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
