contentColumnType: string
fieldGroup: 63c84b53-059e-46e3-b41e-3cd1cb9030fe # Content Builder Fields
handle: image
instructions: 'The image for this section. '
name: Image
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:47d806d7-f955-46cc-9e24-88e5a9334137' # Site Assets
  defaultUploadLocationSubpath: general
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Select an image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:47d806d7-f955-46cc-9e24-88e5a9334137' # Site Assets
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:47d806d7-f955-46cc-9e24-88e5a9334137' # Site Assets
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
