contentColumnType: boolean
fieldGroup: 63c84b53-059e-46e3-b41e-3cd1cb9030fe
handle: isLightbox
instructions: 'Enable to open the target link in a popup (recommended for youtube/vimeo videos).'
name: 'Open Link in Popup'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
