contentColumnType: text
fieldGroup: 7fa5e5f4-59ab-4c6f-9d42-8f827e5e4565
handle: newsletterPopupForm
instructions: 'The form code (or HTML content) to display in the newsletter popup (be careful to use safe HTML code). Form embed codes are easy to create in MailChimp (under Audience > Signup Forms > Embedded Forms). '
name: 'Newsletter Signup - Popup Form'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
