fieldLayouts:
  62516416-708d-4a7c-b323-597e20b8a716:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 9075a3a8-280c-41d1-96e2-348beb518b13
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: footerNavigation
hasTitleField: false
name: 'Footer Navigation'
section: 70e8051d-b22c-4014-b436-a4430f341640
sortOrder: 1
titleFormat: '{navigationLink.getText()}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
