fieldLayouts:
  4f4931b4-7bfa-4677-bbd6-6d81000ce93c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: 'The business name of this partner'
            label: 'Partner Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: f7a6d15c-0dbc-4167-ac30-a19f8f45491d # Image
            instructions: 'The primary logo to use for this partner. '
            label: 'Partner Logo'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d7af6a87-c305-4903-b8bd-34ca93b30179 # URL
            instructions: 'The URL of this partner''s website'
            label: 'Partner Website'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: partners
hasTitleField: true
name: Partners
section: db958bcb-a6d8-4133-963d-dc2b3577160d # Partners
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
