dateModified: 1634663662
email:
  fromEmail: $SYSTEM_EMAIL
  fromName: $SITE_NAME
  replyToEmail: null
  template: ''
  transportSettings:
    apiKey: $MAILGUN_API_KEY
    domain: $MAILGUN_DOMAIN
    endpoint: $MAILGUN_ENDPOINT
  transportType: craft\mailgun\MailgunAdapter
plugins:
  async-queue:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  calendarize:
    edition: standard
    enabled: true
    schemaVersion: 1.3.0
  child-me:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: OOO7H8GXYFYPO8MLWXW0UPWK
    schemaVersion: 1.1.8
    settings:
      alertEmails: null
      defaultDateDisplayType: ''
      defaultDateTime:
        __assoc__:
          -
            - date
            - ''
          -
            - timezone
            - America/Los_Angeles
          -
            - time
            - ''
      defaultDateValueOption: ''
      defaultEmailTemplate: ''
      defaultFileUploadVolume: 'folder:3628224c-b498-4d54-b48c-e1b13ac90c05' # Form Uploads
      defaultFormTemplate: defaultForm
      defaultInstructionsPosition: verbb\formie\positions\BelowInput
      defaultLabelPosition: verbb\formie\positions\AboveInput
      defaultPage: submissions
      enableUnloadWarning: '1'
      maxIncompleteSubmissionAge: 30
      maxSentNotificationsAge: 30
      pluginName: Formie
      saveSpam: true
      sendEmailAlerts: false
      sentNotifications: true
      spamBehaviour: showSuccess
      spamBehaviourMessage: ''
      spamKeywords: ''
      spamLimit: 500
      useQueueForIntegrations: true
      useQueueForNotifications: true
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  logs:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  neo:
    edition: standard
    enabled: true
    licenseKey: ZG88CFP7QSR4UMOYKJSAM4QK
    schemaVersion: 2.8.16
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  related-entry-types:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.1.1
    settings:
      description: ''
      facebookAppId: ''
      metaTemplate: _partials/global/meta
      removeAlternateUrls: ''
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if getenv('ENVIRONMENT') != 'live' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage: ''
      title:
        -
          __assoc__:
            -
              - key
              - '1'
            -
              - locked
              - '0'
            -
              - template
              - '{title}'
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '1'
            -
              - template
              - ' - {{ siteName }}'
      titleSuffix: null
      twitterHandle: ''
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $SITE_NAME
  retryDuration: null
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
